name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.2.5 [CE|EE|ECE 2.4.0-2.4.7] 03 Jul 2024
          tag_name: 1.2.5
          body: |-
            ### softcommerce/module-url-rewrite-generator [1.2.5]
            - **Feature**: Add an option to generate product url_key value by store scope [#12]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
