name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.2.0 [CE|EE|ECE 2.4.0-2.4.7] 15 Apr 2024
          tag_name: 1.2.0
          body: "New functionality to import URL rewrites from CSV file [#7]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
