name: Automated Release
on:
  push:
    branches:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: 1.2.2 [CE|EE|ECE 2.4.0-2.4.7] 17 Apr 2024
          tag_name: 1.2.2
          body: "Allow fully qualified domain names in the `request_path` and `target_path` fields for URL rewrite import. [#9]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
